#!/bin/bash

BASEDIR=/root/accserver

mkdir -p ${BASEDIR}/local/{cfg,log,results}

docker run --name accserver --rm --detach \
  -v ${BASEDIR}/app/server:/opt/server \
  -v ${BASEDIR}/local/cfg:/opt/server/cfg \
  -v ${BASEDIR}/local/log:/opt/server/log \
  -v ${BASEDIR}/local/results:/opt/server/results \
  -p 9232:9232/tcp \
  -p 9231:9231/udp \
  mafalitic/accserver:latest
